# Change these first
owner: francoZuniga32 # Your GitHub organization or username, where this repository lives
repo: pedco-status # The name of this repository

sites:
  - name: FAI-web
    url: https://faiweb.uncoma.edu.ar/
  - name: PEDCO
    url: https://pedco.uncoma.edu.ar/
  - name: SIU Guarani
    url: https://siufai.uncoma.edu.ar/informatica
  - name: Debian FAI
    url: http://debianfai.fi.uncoma.edu.ar/
  - name: CEFAI
    url: https://cefai.fi.uncoma.edu.ar/

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /pedco-status
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Upptime
  introTitle: "**Upptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  introMessage: This is a sample status page which uses **real-time** data from our [GitHub repository](https://github.com/upptime/upptime). No server required — just GitHub Actions, Issues, and Pages. [**Get your own for free**](https://github.com/upptime/upptime)
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
